/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.epam.lab;

import org.apache.commons.lang3.math.NumberUtils;

public class StringUtils {

    private static final double ZERO_VALUE = 0d;

    public boolean isPositiveNumber(String str) {

        Double number = NumberUtils.createDouble(str);
        return (number.compareTo(ZERO_VALUE) > ZERO_VALUE);
    }
}
