/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.epam.lab;

import com.epam.lab.StringUtils;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class StringUtilsTest {

    private static final String POSITIVE_VALUE = "45";

    @Test void isPositiveNumberMethodShouldReturnTrueWhenPositiveNumberApplied() {
        StringUtils classUnderTest = new StringUtils();
        assertTrue(classUnderTest.isPositiveNumber(POSITIVE_VALUE));
    }
}
